name: tracy-profiler
version: 0.1.0.0
github: "githubuser/tracy-profiler"
license: BSD-3-Clause
author: "Author name here"
maintainer: "example@example.com"
copyright: "2025 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

synopsis: Haskell bindings to libracy
# description:

dependencies:
- base >= 4.7 && < 5

default-extensions:
- BlockArguments

flags:
  manual_lifetime:
    description: Manually manage profiler lifetime
    manual: true
    default: true

library:
  source-dirs: src
  c-sources: cbits/tracy_wrapper.c
  cc-options:
  - -DTRACY_ENABLE
  include-dirs:
  - upstream/tracy/public
  extra-libraries:
  - TracyClient
  - stdc++
  when:
  - condition: flag(manual_lifetime)
    cc-options:
    - -DTRACY_MANUAL_LIFETIME
    cpp-options:
    - -DHS_MANUAL_LIFETIME

tests:
  tracy-profiler-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tracy-profiler
    - tasty
    - tasty-hunit

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
