name: tracy-profiler
version: 0.1.0.0
github: "githubuser/tracy-profiler"
license: BSD-3-Clause
author: "Author name here"
maintainer: "example@example.com"
copyright: "2025 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

synopsis: Haskell bindings to libracy
# description:

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

tests:
  tracy-profiler-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tracy-profiler
    - tasty
    - tasty-hunit

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
